# HTTP Server.
server:
  address: ":8018"
  serverName: "go-ddd"
  mode: "debug"

# Database.
mysql:
  username: "root"
  password: "123456"
  dbHost: "10.4.7.71"
  dbPort: 3306
  dbName: "test"

# Log.
log:
  logFileDir: "./tmp"
  appName: "go-ddd"
  maxSize: 512
  maxBackups: 64
  maxAge: 7

# nsq.
nsq:
  nsq_producer_host: "10.4.7.71"
  nsq_producer_port: 4150 # tcp
  nsq_subscribe_host: "10.4.7.71"
  nsq_subscribe_port: 4150 # tcp

